version: '3.9'

services:
  # Platform application
  platform:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SITE_ID=${SITE_ID}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - SITE_ID=${SITE_ID}
      - NEXT_PUBLIC_SITE_ID=${SITE_ID}
    volumes:
      - ./configs:/app/configs:ro
    restart: unless-stopped
    networks:
      - platform-network

  # Nginx reverse proxy for multi-domain routing
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - platform
    networks:
      - platform-network
    restart: unless-stopped

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - platform-network
    restart: unless-stopped

networks:
  platform-network:
    driver: bridge

volumes:
  redis-data:
